version: "3"

services:
  sandbox:
    container_name: sandbox
    image: oxheadalpha/flextesa:20230915
    command: oxfordbox start
    environment:
      flextesa_node_cors_origin: "*"
      block_time: 3
    ports:
      - 127.0.0.1:8732:20000
