import { b58cencode } from "@taquito/utils";
import blake from "blakejs";

/**
 * Generate a payload hash for PoE Challenge according TZIP-27.
 *
 * Quote: "The payloadHash should have a prefix starting with m, representing as message. It is generated by encoding, Base58CheckEncoding, the payload—resulting from the blake2b hashing with a digit size of 20 bytes—and the prefix in bytes \110"
 * @param payload The payload of Proof of Event Challenge we want to hash according TZIP-27
 *
 * @returns The payload's hash.
 */
export const generatePoEPayloadHash = (payload: string) => {
  const blakeHash = blake.blake2b(payload, undefined, 20);
  // Prefix is 'm' in bytes
  return b58cencode(blakeHash, new Uint8Array([110]));
};
