name: Automatic build and deploy

on:
  push:
    branches:
      - main
      - release
  pull_request:
    branches:
      - main
      - release

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install deps
        run: npm install
      - name: Build app
        run: |
          ./node_modules/.bin/next build
          ./node_modules/.bin/next export -o build
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: build

  deploy:
    # Add a dependency to the build job
    needs: build

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write # to deploy to Pages
      id-token: write # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    # This doesn't seem to work yet
    # environment:
    #  name: github-pages
    #  url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        if: ${{ ! github.event_name != 'pull_request' && github.ref == 'refs/heads/release' }}
        id: deployment
        uses: actions/deploy-pages@v4
